name: cuqter
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  firebase_storage: ^13.1.0
  cloud_firestore: ^6.1.3
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  flutter_native_splash: ^2.4.7
  assets: ^0.0.2
  http: ^1.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
    color: "BDA6CE"
    web: true
    android: true
    ios: true
    branding: assets\icon\branding.png
    image: assets\icon\icon.png

    android_12: 
      color: "BDA6CE"
      branding: assets\icon\branding.png
      image: assets\icon\icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  web:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  