// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvtzNFHyoCeq8pZZ_JdaG0dmd4a1DPHs',
    appId: '1:921725231252:web:a2dbfa0c97694cbf299481',
    messagingSenderId: '921725231252',
    projectId: 'cuqter-2fa01',
    authDomain: 'cuqter-2fa01.firebaseapp.com',
    databaseURL: 'https://cuqter-2fa01-default-rtdb.firebaseio.com',
    storageBucket: 'cuqter-2fa01.firebasestorage.app',
    measurementId: 'G-5TKLZ0RS2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMRHTUsoptsjL8WLzzbQ2pK4kBfGY_5U',
    appId: '1:921725231252:android:15df51907ca8af78299481',
    messagingSenderId: '921725231252',
    projectId: 'cuqter-2fa01',
    databaseURL: 'https://cuqter-2fa01-default-rtdb.firebaseio.com',
    storageBucket: 'cuqter-2fa01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbsbEWFuRrlHLJxsP7iUEiqiuTOao2V54',
    appId: '1:921725231252:ios:60e2d1c0ece688d5299481',
    messagingSenderId: '921725231252',
    projectId: 'cuqter-2fa01',
    databaseURL: 'https://cuqter-2fa01-default-rtdb.firebaseio.com',
    storageBucket: 'cuqter-2fa01.firebasestorage.app',
    androidClientId: '921725231252-pk2vi5htcjc0qak8tos5ald4enbi3uvl.apps.googleusercontent.com',
    iosClientId: '921725231252-plfauvgtjfit4vrbr2qst2j64h26n7fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuqter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbsbEWFuRrlHLJxsP7iUEiqiuTOao2V54',
    appId: '1:921725231252:ios:60e2d1c0ece688d5299481',
    messagingSenderId: '921725231252',
    projectId: 'cuqter-2fa01',
    databaseURL: 'https://cuqter-2fa01-default-rtdb.firebaseio.com',
    storageBucket: 'cuqter-2fa01.firebasestorage.app',
    androidClientId: '921725231252-pk2vi5htcjc0qak8tos5ald4enbi3uvl.apps.googleusercontent.com',
    iosClientId: '921725231252-plfauvgtjfit4vrbr2qst2j64h26n7fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuqter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOvtzNFHyoCeq8pZZ_JdaG0dmd4a1DPHs',
    appId: '1:921725231252:web:77e847220ebb6f9f299481',
    messagingSenderId: '921725231252',
    projectId: 'cuqter-2fa01',
    authDomain: 'cuqter-2fa01.firebaseapp.com',
    databaseURL: 'https://cuqter-2fa01-default-rtdb.firebaseio.com',
    storageBucket: 'cuqter-2fa01.firebasestorage.app',
    measurementId: 'G-1ZE66HBFEY',
  );
}
